# Uncomment the next line to define a global platform for your project
platform :ios, '15.5'

target 'LearnCocoapods' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire'
  pod 'SnapKit', '~> 5.0.0'
  pod 'Kingfisher', '~> 7.0'
  pod 'FLEX'
  pod 'IQKeyboardManagerSwift'
  pod 'SwiftGen'
  pod 'SwiftLint'

end
